### ISSUE TITLE
Build and add the zip file to be installed as module

### ISSUE THREAD

**Issue by vasilestefirta** [hansemannn/titanium-firebase-analytics#1]
Hi @hansemannn,

Big thanks for starting working on this module :clap:

Could you please build and upload a ready-to-go file we can use to install this module in a project?
I mean something similar with what was done in this repo (see how the **ti.firebase-iphone-1.3.1.zip** file which is part of the repo):
https://github.com/chrisribe/ti-firebase

Thanks!

**Comment by trkfabi** [comment]
Hi @vasilestefirta, 

you can find it here: https://github.com/hansemannn/titanium-firebase-analytics/releases

**Comment by vasilestefirta** [comment]
Thanks @trkfabi,

That's good to know! Totally forgot to check the **release** section :simple_smile:. Are there any plans for an Android release? That's the one I'm mainly looking for ATM 🙏

**Comment by hansemannn** [comment]
Hey there, the release might be outdated, I‘ll draft the final version tomorrow. For Android, a few methods have already been implemented, bur it will require 6.3.1 to build (which will fix possible google-playservices once and forever). 

Also, this whole effort needs more Android devs participating, so feel free to help out!

**Comment by hansemannn** [comment]
Updated the latest releases, see the [releases tab](https://github.com/hansemannn/titanium-firebase-analytics/releases) for more infos!
