### ISSUE TITLE
Not getting data on Android

### ISSUE THREAD

**Issue by trkfabi** [hansemannn/titanium-firebase-analytics#10]
Hi,

I'm using analytics and core just to log some events. iOS works fine but I don't see any data going to Firebase under the Android project.
Settings seem to be just fine, the google-services.json is under /app/assets/android/ and no errors are begin logged in the console.
I'm using Ti SDK 6.3.0 and I don't use any other module that could conflict with this one.

I'd appreciate any clue of where to look at.

Thanks

**Comment by hansemannn** [comment]
I do not personally use the Android one, but maybe @miga or @appwerft can help?

**Comment by mitulbhalia** [comment]
Hello @trkfabi 
Did you find any solution for your issue?
Also can you please tell me how to configure android module?
I added google-services.json in /app/assets/android/ but when i tried run the demo, it shows me below error.

Uncaught TypeError: Alloy.Globals.FA.configure is not a function

I declare this module in alloy.js as below
Alloy.Globals.FA = require('firebase.analytics');
Alloy.Globals.FA.configure();
Please let me know.

**Comment by trkfabi** [comment]
Hi Mitul,

No, I haven’t found a solution yet. I’m not receiving any data from the Android apps on the firebase console.

I have added these 2 lines to tiapp.xml:
<module platform="android" version="1.0.1">firebase.analytics</module>
<module platform="android" version="1.0.1">firebase.core</module>

And this is the code in Alloy.js:
Alloy.Globals.FirebaseCore = require('firebase.core');
Alloy.Globals.FirebaseAnalytics = require('firebase.analytics');
Alloy.Globals.FirebaseCore.configure();

and I call this method:
Alloy.Globals.FirebaseAnalytics.log(eventName, parms);

it works on iOS.

and this is my app/assets folder:



Hope we can find a solution or workaround to this issue.

Fabian

**Comment by hansemannn** [comment]
I noticed that you use an outdated version of the module that didn't play nice with playservices at that time. With 7.0.0+, the google play services are managed in a central place, the [ti.playservices](https://github.com/appcelerator-modules/ti.playservices/releases) module. The updated module version (2.x) requires that module and firebase.core to be included. 

Example:
```xml
<module>ti.playservices<module>
<module>firebase.core<module>
<module>firebase.analytics<module>
```

In addition, if the problem still occurs with titanium-firebase-analytics 2.0.0 (current stable), I've prepared a 2.0.1 version that attempts to pass the activity different than before. Let me know if that works out!

Preprelease:
[firebase.analytics-android-2.0.1.zip](https://github.com/hansemannn/titanium-firebase-analytics/files/1596252/firebase.analytics-android-2.0.1.zip)

**Comment by mitulbhalia** [comment]
Ok @trkfabi  Let me know when you find solution.

@hansemannn My main concern is that i am not using latest version of mac os so i need to use ti sdk 7.0 then i have to first update my mac os then xcode version so is there any older which i can use for my iphone app?

**Comment by trkfabi** [comment]
Hi Hans,

thank you for the update.
I don’t know if I am missing something…

I had to install node 8.x to use Ti sdk 7.x+.

I replaced tiapp.xml lines with this:


it compiles without errors for both iOS and Android, but it crashes when the app runs with this error on iOS and Android:








I pasted the modules in both folders, under the “modules” folder in the project and in /library/…







I don’t know what’s going on :(((

Fabian.

**Comment by hansemannn** [comment]
Sorry, I think your post is missing some screens / code.

**Comment by trkfabi** [comment]
Sorry. I have updated the post.

**Comment by trkfabi** [comment]
OMG, wait... I copied/paste <module>firebase.analytics<module> from somewhere.... the closing tag is wrong!! (i'm crying)

**Comment by hansemannn** [comment]
I've just changed an activity reference to initialize the instance and now the app doesn't crash for me anymore. Unfortunately, I still receive the following logs on Android when logging with `Analytics.log('test_event', {});`. 

It says:
```
[INFO]  FA: App measurement is starting up, version: 11020
[INFO]  FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
[ERROR] FA: GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.
[ERROR] FA: Scheduler not set. Not logging error/warn
[INFO]  FA: To enable faster debug mode event logging run:
[INFO]  FA:   adb shell setprop debug.firebase.analytics.app com.appc.firebasedemo
[ERROR] FA: AppMeasurementReceiver not registered/enabled
[ERROR] FA: AppMeasurementService not registered/enabled
[ERROR] FA: Uploading is not possible. App measurement disabled
[INFO]  FA: Tag Manager is not found and thus will not be used
```

Probably pasted the `google-services.json` incorrectly? I only personally tested the iOS version so far, so if we can get Android running together, we should be good!

**Comment by trkfabi** [comment]
I'm not Android fan neither but a client insists in using Firebase.
I got rid of some errors/warnings by adding these services to the tiapp.xml under `<application>` tag:

```
<!-- this is to make FA work -->
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false"/>	

<service android:name="mypackagename.gcm.GcmIntentService" android:exported="false">
   <intent-filter>
      <action android:name="com.google.android.c2dm.intent.RECEIVE" />
   </intent-filter>
</service>

<service android:name="mypackagename.gcm.GcmIntentService" android:exported="false">
   <intent-filter>
      <action android:name="com.google.android.c2dm.intent.SEND" />
   </intent-filter>
</service>

<service android:name="mypackagename.gcm.GcmIDListenerService" android:exported="false">
   <intent-filter>
      <action android:name="com.google.android.gms.iid.InstanceID" />
   </intent-filter>
</service>

 <service android:name="mypackagename.gcm.RegistrationIntentService" android:exported="false"/>
<!-- this is to make FA work -->
```

and algo had to add `<string name="google_app_id">my firebase application id</string>` to the string.xml file (still looking if there's a better place to set this prop, i.e: tiapp.xml like gsm.senderid)

but I don't receive any event yet.

**Comment by trkfabi** [comment]
Custom parameters are not working on Android.
This sentence: `Alloy.Globals.FirebaseAnalytics.log('logout', {username: "a4@a.com"});`

logs this on Android:
![image](https://user-images.githubusercontent.com/1564477/34506120-b0cd8240-f008-11e7-9487-f961caef1281.png)

and this on iOS:
![image](https://user-images.githubusercontent.com/1564477/34506132-d529bf8c-f008-11e7-81f3-3f5f82d13904.png)

**Comment by hansemannn** [comment]
Thanks @trkfabi, great progress! The custom events are only not working, because it right now checks for dedicated custom keys like [`ACHIEVEMENT_ID`](https://github.com/hansemannn/titanium-firebase-analytics/blob/master/android/src/firebase/analytics/TitaniumFirebaseAnalyticsModule.java#L52).

I think we can remove that check and just bridge all String keys to it. Let me see how other do that. I'll also update the readme today to reflect the installation steps.

**Comment by hansemannn** [comment]
Added an own paragraph for the installation [here](https://github.com/hansemannn/titanium-firebase-analytics/blob/master/README.md#installation). Closing this issue, will likely do a PR to add custom events.

**Comment by hansemannn** [comment]
2.0.1 drafted, including an attempt to implement custom events: https://github.com/hansemannn/titanium-firebase-analytics/releases/tag/android-2.0.1

**Comment by trkfabi** [comment]
custom events are working fine with the latest 2.0.1.
well done!

**Comment by DGJMaxwell** [comment]
Excellent work! However, I had to add another service in the AndroidManifest section of the `tiapp.xml` file, this allowed the App Measurement Service to run:
```
<service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:permission="android.permission.BIND_JOB_SERVICE"/>
```

Without this addition, I still received:

    [ERROR] FA: AppMeasurementReceiver not registered/enabled
    [ERROR] FA: AppMeasurementService not registered/enabled

**Comment by hansemannn** [comment]
Thanks @DGJMaxwell, added that note!

**Comment by hansemannn** [comment]
.. and an example app: https://github.com/hansemannn/titanium-firebase-demo

**Comment by LilianAlvarez** [comment]
I experimented the same issue reported by Fabian Martinez with firebase analytics. I can not figure it out how to setup firebase analytics.

I get the same error : GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.

I did add the <string name="google_app_id">1:1XXXXXX:android:XXXXXXXX</string> in platform/android/res/values

I added the google-services.json in assets/android 

I added the require info in the tiapp.xml
<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false"/>	

<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true">
   <intent-filter>
      <action android:name="com.google.android.gms.measurement.UPLOAD" />
   </intent-filter>
</receiver>  

<service android:name="mypackagename.gcm.GcmIntentService" android:exported="false">
   <intent-filter>
      <action android:name="com.google.android.c2dm.intent.RECEIVE" />
   </intent-filter>
</service>

<service android:name="mypackagename.gcm.GcmIntentService" android:exported="false">
   <intent-filter>
      <action android:name="com.google.android.c2dm.intent.SEND" />
   </intent-filter>
</service>

<service android:name="mypackagename.gcm.GcmIDListenerService" android:exported="false">
   <intent-filter>
      <action android:name="com.google.android.gms.iid.InstanceID" />
   </intent-filter>
</service>

 <service android:name="mypackagename.gcm.RegistrationIntentService" android:exported="false"/>


My Tiapp.xml : 

<module platform="iphone">ti.map</module>
      <module platform="android" version="4.0.0">ti.map</module>
      <module platform="android">ti.playservices</module>
      <module platform="commonjs">ti.cloud</module>
      <module platform="android">ti.cloudpush</module>
      <module platform="iphone">dk.napp.social</module>
      <module>firebase.core</module>
      <module>firebase.analytics</module>
      <module platform="iphone">facebook</module>

**Comment by trkfabi** [comment]
I used to get this error, but it’s related to the google app id you added in res/values. It’s not finding it for some reason.

Can you share exactly how you added the tag and the name of the file under res/values folder?

**Comment by LilianAlvarez** [comment]
Here it is @trkfabi. In my strings.xml i added : 
<string name="google_app_id">1:10XXXXXX3:android:XXXXXXXXXa</string>

![capture d ecran 2018-01-19 a 00 48 04](https://user-images.githubusercontent.com/26827633/35127441-73ee2738-fcb2-11e7-9225-c92370df0721.png)

**Comment by trkfabi** [comment]
Try replacing the strings contents with:

<string name="google_app_id">1:10XXXXXX3:android:XXXXXXXXXa</string>

**Comment by LilianAlvarez** [comment]
I try and i still get the same error @trkfabi 

[ERROR] FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI

**Comment by trkfabi** [comment]
try adding it to:

app/i18n/en/string.xml  
or
app/i18n/es/string.xml  

or the language folder you are using, as if it was just another language text id.
(not the best but it may work)

**Comment by LilianAlvarez** [comment]
@trkfabi : thanks for the lead i got it work by using the international system.

Thanks a lot @trkfabi !
