### ISSUE TITLE
v2.0.0 Android not installing on gittio

### ISSUE THREAD

**Issue by anik786** [hansemannn/titanium-firebase-analytics#12]
I cannot seem to install v2.0.0 for android using gittio, despite it being released a few days back.

```
$ gittio install firebase.analytics@2.0.0
[INFO]  firebase.analytics searching...
[ERROR] firebase.analytics@2.0.0:android not found
[ERROR] firebase.analytics@2.0.0:ios not found
```

**Comment by hansemannn** [comment]
The version was released 4 days ago, probably gittio did not crawl the new version so far. You can just install it from the [Releases Tab](https://github.com/hansemannn/titanium-firebase-analytics/releases/tag/android-2.0.0) without problems.
