### ISSUE TITLE
Can't build for neither iOS or Android

### ISSUE THREAD

**Issue by amigoni** [hansemannn/titanium-firebase-analytics#14]
SDK 7.0.1

    [ERROR] :  TiApplication: (main) [90,2388] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fluidmarket.fluids-2/base.apk"],nativeLibraryDirectories=[/data/app/com.fluidmarket.fluids-2/lib/arm, /data/app/com.fluidmarket.fluids-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libfirebase.core.so"; Titanium 7.0.1,2017/12/18 10:42,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fluidmarket.fluids-2/base.apk"],nativeLibraryDirectories=[/data/app/com.fluidmarket.fluids-2/lib/arm, /data/app/com.fluidmarket.fluids-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libfirebase.core.so"
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:1076)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  TiApplication: 	at com.fluidmarket.fluids.FluidApplication.onCreate(FluidApplication.java:79)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$1800(ActivityThread.java:221)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:158)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:7224)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: main
[ERROR] :  AndroidRuntime: Process: com.fluidmarket.fluids, PID: 14045
[ERROR] :  AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fluidmarket.fluids-2/base.apk"],nativeLibraryDirectories=[/data/app/com.fluidmarket.fluids-2/lib/arm, /data/app/com.fluidmarket.fluids-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libfirebase.core.so"
[ERROR] :  AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
[ERROR] :  AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  AndroidRuntime: 	at com.fluidmarket.fluids.FluidApplication.onCreate(FluidApplication.java:79)
[ERROR] :  AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:221)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
[ERROR] :  AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
[ERROR] :  AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7224)
[ERROR] :  AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[ERROR] :  AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Get the above error on Android, on iOS it simply crashes at boot. Seems the firebasecore can't be found.

**Comment by maronaquillo** [comment]
@amigoni You also need to include the [titanium-firebase-core](https://github.com/hansemannn/titanium-firebase-core) to make it work.

**Comment by hansemannn** [comment]
Yes, thats your issue. Thanks @maronaquillo for helping out, this is how communities are kept alive :).

**Comment by amigoni** [comment]
I tried both enabling and disabling the commonJS part of the firebase core. Either one didn't work.
    <modules>
        <module platform="commonjs">To.ImageCache</module>
        <module platform="iphone">ti.imagefactory</module>
        <module platform="android">ti.imagefactory</module>
        <module platform="iphone" version="5.4.0">facebook</module>
        <module platform="android">facebook</module>
        <module platform="iphone">dk.napp.social</module>
        <module platform="iphone">com.appcelerator.urlSession</module>
        <module platform="iphone">ti.map</module>
        <module platform="android">ti.map</module>
        <module platform="iphone">com.joseandro.uniqueids</module>
        <module platform="iphone">ti.ga</module>
        <module platform="iphone">co.uk.devpulse.tiadwords</module>
        <module platform="iphone">yy.logcatcher</module>
        <module platform="android">yy.logcatcher</module>
        <module platform="android">ti.adjust</module>
        <module platform="iphone">ti.adjust</module>
        <module platform="commonjs">nl.fokkezb.html2as</module>
        <module platform="android">fh.imagefactory</module>
        <module platform="iphone">com.mfogg.squarecamera</module>
        <module platform="windows">hyperloop</module>
        <module platform="iphone">hyperloop</module>
        <module platform="android">bencoding.android.tools</module>
        <module platform="android">ti.goosh</module>
        <module platform="iphone">ti.wkwebview</module>
        <module platform="iphone">ti.reviewdialog</module>
        <module platform="iphone">com.utils.qrscanner</module>
        <module platform="android">com.utils.qrscanner</module>
        <module platform="android">ti.playservices</module>
        <module platform="iphone">firebase.analytics</module>
        <module platform="android">firebase.analytics</module>
        <module platform="iphone">firebase.core</module>
        <module platform="android">firebase.core</module>
        <module platform="commonjs">firebase.core</module>
    </modules>

**Comment by hansemannn** [comment]
@amigoni There is no firebase.core module, maybe something uses "my" module ID for something else?

**Comment by amigoni** [comment]
Not sure I understand what you mean. The project doesn't see the firebase.core module? 
Here is the setup. 

Firebase Analytics: Android 2.0.1 iOS 1.1.0
Firebase Core: Android 2.0.0 iOS 1.0.0 CommonJS 1.0.0
Titanium 7.0.1

Thanks so much for the help.

**Comment by hansemannn** [comment]
There is no Firebase CommonJS module, at least not from myself. So if you have one, maybe someone build it, but its not compatible with this module architecture (core + [analytics/cloud-messaging/crash-reporting/...]).

**Comment by amigoni** [comment]
Mmm. Must have dropped them in the wrong folder by mistake. I removed them from the folder and the tiapp but still no luck crash at boot

**Comment by hansemannn** [comment]
Can you attach a sample project with this behavior?

**Comment by amigoni** [comment]
Let me give it a shot. I'm sure there is an issue with my project and in a new project there won't be this issue. I will try to import all the modules. If that doesn't succeed we are in a catch22 situation. Meaning by me trying to make the project will get me to find the solution. Could you decipher what that error means? Maybe it will give me a hint of where to look. Thanks

**Comment by hansemannn** [comment]
I'd remove all references to the firebase-modules in `<project>/modules/android` and `~/Library/Application Support/Titanium/modules/android`, unzip the modules in your project again and try it again. It could use an outdated version in a different directory, hard to explain.

**Comment by hansemannn** [comment]
Re-closing as it's a project issue.

**Comment by amigoni** [comment]
Still no luck. Going through and trying to remove modules one by one

**Comment by amigoni** [comment]
Well the issue was a lot more trivial than I thought. I was calling FirebaseAnalytics.configure() instead of FirebaseCore.configure(). That's what caused the crash.

**Comment by amigoni** [comment]
Unfortunately I am finding more and more issues. If I have this line of code from your example. I crash. Ti.API.info('App Instance ID: ' + FirebaseAnalytics.appInstanceID); @hansemannn It seems that instead of getting an error it just crashes. But I shouldn't be getting an error unless it can't find that appInstanceID.

**Comment by amigoni** [comment]
@hansemannn Confirmed. Everything seems to work now but I had to remove that line of code:
    Ti.API.info('App Instance ID: ' + FirebaseAnalytics.appInstanceID); 
All other to work no problems.

**Comment by hansemannn** [comment]
Please note that its an iOS only property and only works if you have a valid session running already.

**Comment by amigoni** [comment]
Thanks @hansemannn. Will note that.
