### ISSUE TITLE
-[__NSCFConstantString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x10ca908f0

### ISSUE THREAD

**Issue by DouglasHennrich** [hansemannn/titanium-firebase-analytics#20]
- TiSDK `7.1.0.GA`

- Firebase Analytics `1.1.1`

- Platform `iOS`

Trying to log a event without options but it fails.

```
FirebaseAnalytics.log(event, params);   // event -> "product_250_appear" params => null
```

If I put just an empty object it won't log on firebase's dashboard

**Comment by DouglasHennrich** [comment]
ping @hansemannn

**Comment by hansemannn** [comment]
Sorry, no time for open source work right now.

**Comment by hansemannn** [comment]
I just tested it and it seems to work fine. Please use 1.3.0 for testing, thx!
