### ISSUE TITLE
Exception Thrown

### ISSUE THREAD

**Issue by DCareClues** [hansemannn/titanium-firebase-analytics#25]
Getting bellow exception randomly while logging event, analytics.log(eventName, params). I have included "firebase.core" and "firebase.analytics" in alloy.js. 

```Uncaught Attempt to invoke virtual method 'android.content.Context android.content.ContextWrapper.getApplicationContext()' on a null object reference```

**Comment by hansemannn** [comment]
Please try with v2.1.1, thanks!

**Comment by hansemannn** [comment]
Okay, now I know why. You need to have a window opened before initializing the Firebase instance, otherwise the native activity may not be available. Please update your code accordingly and try again, thx!
