### ISSUE TITLE
Android FirebaseInstanceId

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-firebase-analytics#26]
When my app runs I'm getting the following error

[ERROR] :  FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
[ERROR] :  FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.

I've ensured I'm using the correct mobilesdk_app_id in the strings.xml file

Any other ideas why this is happening?

**Comment by Wingee** [comment]
Thanks for that, but that doesn't resolve my issue. i've already followed those steps

Here is my application tag

`            <application android:theme="@style/Theme.skitanium">
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
                <service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false" />
				<service android:name="com.google.android.gms.measurement.AppMeasurementJobService" android:permission="android.permission.BIND_JOB_SERVICE" android:enabled="true" android:exported="false" />

				<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true">
				   <intent-filter>
					  <action android:name="com.google.android.gms.measurement.UPLOAD" />
				   </intent-filter>
				</receiver>  
				<service android:name="com.ingelby.something.gcm.GcmIntentService" android:exported="false">
				   <intent-filter>
					  <action android:name="com.google.android.c2dm.intent.RECEIVE" />
				   </intent-filter>
				</service>
				<service android:name="com.ingelby.something.gcm.GcmIntentService" android:exported="false">
				   <intent-filter>
					  <action android:name="com.google.android.c2dm.intent.SEND" />
				   </intent-filter>
				</service>
				<service android:name="com.ingelby.something.gcm.GcmIDListenerService" android:exported="false">
				   <intent-filter>
					  <action android:name="com.google.android.gms.iid.InstanceID" />
				   </intent-filter>
				</service>
				 <service android:name="com.ingelby.something.gcm.RegistrationIntentService" android:exported="false"/>
            </application>`

**Comment by Wingee** [comment]
and my strings.xml file

`
<?xml version="1.0" encoding="UTF-8"?>
<resources>
	<string name="google_app_id">1:724774800604:android:29792afghfghfghfghfghfg</string>
</resources>
`

**Comment by hansemannn** [comment]
Reopening for community help, but I am currently unable to assist.

**Comment by Wingee** [comment]
It appears that that error doesn't affect getting data into FA.

From a little further digging I don't believe this part is necessary for FA:

`			<service android:name="MY_PACKAGE_NAME.gcm.GcmIntentService" android:exported="false">
			   <intent-filter>
				  <action android:name="com.google.android.c2dm.intent.RECEIVE" />
			   </intent-filter>
			</service>

			<service android:name="MY_PACKAGE_NAME.gcm.GcmIntentService" android:exported="false">
			   <intent-filter>
				  <action android:name="com.google.android.c2dm.intent.SEND" />
			   </intent-filter>
			</service>

			<service android:name="MY_PACKAGE_NAME.gcm.GcmIDListenerService" android:exported="false">
			   <intent-filter>
				  <action android:name="com.google.android.gms.iid.InstanceID" />
			   </intent-filter>
			</service>`

And I think it was clashing with another module I'm using for push notifications. Perhaps that section could be removed from the readme

**Comment by hansemannn** [comment]
Updated the readme.

**Comment by AppWerft** [comment]
I have the same issue with my extension of auth module. If I call on JS layer 

```javascript
FirebaseAuth.verifyPhoneNumber({
	phoneNumber : win.children[0].getValue(),
	oncodesent : onCodeSent,
	onverificationcompleted : onVerificationCompleted,
	onerror : onError
});
```
I run in same issue.
