### ISSUE TITLE
FireBase Dynamic Links

### ISSUE THREAD

**Issue by anik786** [hansemannn/titanium-firebase-analytics#27]
(Sorry I wasen't sure where to ask this)

When will you be adding FireBase dynamic links as described here:
https://firebase.google.com/docs/dynamic-links/

It doesn't seem to be in the feature list mentioned here:
https://github.com/hansemannn/titanium-firebase

MANY THANKS and GREAT WORK 😄

**Comment by hansemannn** [comment]
Dynamic links are not supported so far, sorry!

**Comment by anik786** [comment]
Ah man. Any approximate plans on when it is being added?

**Comment by hansemannn** [comment]
It's a community based project, so it depends on developers adding it. If you have clients requesting it, you can consult developers to implement it for you (paid) if that's an option.
