### ISSUE TITLE
[iOS] Support Ads framework

### ISSUE THREAD

**Issue by chmiiller** [hansemannn/titanium-firebase-analytics#3]
First of all I would like to thank you for this awesome module. I've been using it for iOS for 2 weeks already and everything seems to work perfect!
I'm setting my **user properties** on Firebase analytics and I'm missing some of them like gender or age. Then I found this message on [Firebase's iOS documentation](https://firebase.google.com/docs/analytics/ios/properties): 

> The Age, Gender, and Interests properties are automatically collected only if your app links to the [Ad Support framework](https://developer.apple.com/documentation/adsupport). Linking to this framework also automatically collects the Advertising Identifier (IDFA).

I have no idea how to set this property on my Titanium iOS app, can you give me some help?
If this is something to be implemented I can have a deep look at the module although I'm not very good on native Obj-c code 😬

Thanks!

**Comment by hansemannn** [comment]
Thanks Carlos, happy this project is adopted already! Let me take a quick peek into supporting it. Technically, if you append the `-framework AdSupport` in the module.xcconfig, the framework will be linked and the Firebase console should show it.

**Comment by hansemannn** [comment]
=> [1.1.0](https://github.com/hansemannn/titanium-firebase-analytics/releases/tag/ios-1.1.0)
