### ISSUE TITLE
Set User Property Not Working

### ISSUE THREAD

**Issue by jabele** [hansemannn/titanium-firebase-analytics#32]
I am able to log all events to Firebase but not any User Properties. This is happening on both iOS and Android using:

Firebase Core (3.0.2 on Android and 2.2.0 on iOS)
Firebase Analytics (2.1.1 on Android and 1.4.1 on iOS)
Ti.PlayServices (11.0.40)
Titanium SDK (7.5.0 GA and the two most recent nightly builds of 7.5.1)

This is what I am using to set it:

FirebaseAnalytics.setUserPropertyString({
	name: myAppNum,
	value: 163
});

Any reason why this would not be showing even days later in Firebase Analytics?

**Comment by jabele** [comment]
As a follow up to this it looks like there were two things happening. Android is running fine in the example above but took 4 days to show up in Firebase Analytics, but now it is showing up normally. In addition, I tried the previous version of iOS (1.4.0) and now iOS is working as expected as well. It appears this feature is not working on iOS 1.4.1 at the moment.

**Comment by hansemannn** [comment]
There isn't anything special we're doing here, so I'm  not sure how to help :(
