### ISSUE TITLE
ScreenClass always defaults to 'TiViewController'

### ISSUE THREAD

**Issue by RipCazza** [hansemannn/titanium-firebase-analytics#38]
Hello,

I don't seem to be able to set `ScreenClass` and `ScreenName` with `setScreenNameAndScreenClass()`. It appears to always get logged as 'TiViewController' in the Firebase console.

I am calling `setScreenNameAndScreenClass()` in the controller of my window.
I am using version 2.2.2 on Titanium SDK 7.5.0.

it may well be my ineptitude with Firebase and native development. If so, I welcome any directions on the correct implementation. Are there any restraints I should be adhering to regarding `ScreenClass` and `ScreenName`?

Many thanks in advance!

**Comment by hansemannn** [comment]
See #34 for details on this.

**Comment by m1ga** [comment]
```
Alloy.Globals.FirebaseAnalytics.setScreenNameAndScreenClass({
	screenName: "Im Fokus",
	screenClass: "Im Fokus"
});
```
works fine on Android for me but my iOS devices log TiActivity/TiViewController. #34 is talking about Android but that works fine for me and I set the screenClass so I'm not sure why it still uses the default value

iOS version 1.4.1
