### ISSUE TITLE
Android: FirebaseInstanceIdService Timeout

### ISSUE THREAD

**Issue by awarnes** [hansemannn/titanium-firebase-analytics#39]
Hello, and thank you for making this module! I'm trying to get the Android side of it working for basic analytics (really just need the total users). iOS has been working fine in the app, but Android keeps failing around a service timeout on `.../com.google.firebase.iid.FirebaseInstanceIdService`. I'm sure I have a setting wrong, or some other conflict going on but I've been unable to debug it at this point. The full error log: 
[firebase_crash.txt](https://github.com/hansemannn/titanium-firebase-core/files/2954673/firebase_crash.txt) (line 64 shows the timeout error, and line 98 is where the ANR explanation starts). This crash prevents the app from opening/continuing and shows the generic "App Not Responding" error modal.

I've read a few articles about the FirebaseInstanceIdService being deprecated, but figured that it should still be okay if it's working for iOS?

I'm currently using TiSDK 7.4.2.GA, `firebase.core` 3.0.2, and `firebase.analytics` 2.2.2. I've included only the information from the [README.md](https://github.com/hansemannn/titanium-firebase-analytics/blob/master/README.md#android) in the `manifest/application` area.

I've tried building without the `firebase.analytics` module and it works fine (firebase initializes successfully, and the app starts like normal), but of course no information passes through. I've attempted the suggestions in the [Not Getting Data On Android](https://github.com/hansemannn/titanium-firebase-analytics/issues/10) thread, but to no avail. Any help/suggestions would be greatly appreciated! Please let me know if there's anything else you'd need to know to diagnose. Thank you!

**Comment by hansemannn** [comment]
Not using the InstanceIdService in latest versions anymore, since Google also replaced it, so this should not be a deal anymore :-)
