### ISSUE TITLE
build error Android 

### ISSUE THREAD

**Issue by LilianAlvarez** [hansemannn/titanium-firebase-analytics#4]
Hello,

So the module is working fine on iOS but i am having some issue with Android.
When i build the project i get this error : 
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/zza;

Didn't find any solution on google.

![capture d ecran 2017-11-11 a 13 03 12](https://user-images.githubusercontent.com/26827633/32689233-c9f5adde-c6e0-11e7-8801-44a804bf40e4.png)

**Comment by m1ga** [comment]
I have a similar error already with the core package. Is that working for you without the analytics module?

**Comment by m1ga** [comment]
Which modules are you using in your app?
```xml
<modules>
    <module>ti.playservices</module>
    <module>firebase.core</module>
    <module>firebase.analytics</module>
  </modules>
```

**Comment by LilianAlvarez** [comment]
Hello m1ga,

Thanks for reaching out, so yes i have the issue on the firebase core module (even when i remove the analytics module)
I have seen you comment on firebase core issue, i tried to implement the fix by adding the ti.playservices module but i get a "Could not find all required Titanium Modules:
[ERROR]    id: ti.playservices".
I am using the sdk 6.3.0 GA

**Comment by hansemannn** [comment]
Ti.Playservices is made for 7.0.0 by defaut. You can change the minimum version or just recompile it for your needs. I'll try to work on an official guide soon.

**Comment by quentinkb** [comment]
Same problem on my project, when i add both ti.map and firebase.core modules

**Comment by anik786** [comment]
I just reported this issue:
https://github.com/hansemannn/titanium-firebase-core/issues/7

Only affects ti.map v3.3.1 & v3.3.0

Any solution to this problem?

**Comment by hansemannn** [comment]
Please see my comment:
> When being used together with Ti.Map or other modules that use google-play-services, it requires SDK 7.0.0 and the dedicated versions that use the new `ti.playservices` dependency. If running on 7 Beta, use [Ti.Map 4.0.0](https://github.com/appcelerator-modules/ti.map/releases/tag/android-4.0.0).

**Comment by abitul** [comment]
can u help me ?
when i use ti sdk v 7.0.2.GA and i use firebase core 2.0.0 and firebase analytics 2.0.1
i get this error when build in android 

![issue android](https://user-images.githubusercontent.com/33111326/36710373-1b933b2e-1bb0-11e8-9482-3df4f5335e4e.png)

**Comment by m1ga** [comment]
@abitul the error message says that it is in a different module. See this ticket:
https://jira.appcelerator.org/browse/AC-1621
the module is Studio only

**Comment by hansemannn** [comment]
Your https module is not ready for SDK 7.0.0+. Use https 3.0.0+ instead (downloadable via dashboard)

**Comment by abitul** [comment]
I can’t find new module https 3 , because i use free account. Can u help me
?

**Comment by hansemannn** [comment]
Well, then you should never had gotten the module. Its pro and enterprise only. Maybe someone shared it via Github in the past, but the platform validates premium modules as well.
