### ISSUE TITLE
Error when building for android

### ISSUE THREAD

**Issue by RipCazza** [hansemannn/titanium-firebase-analytics#40]
Hello,

I'll preface with a big thanks for all the work that's been put into this library! I seem to be running in some trouble however.
I've previously been able to run my application using this library on android, however, unexplicably, something seems to have gone wrong and I'm now running into erros, even on branches of my application that previously worked.
The error being as followed:
```
[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Event;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Param;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$UserProperty;
[ERROR] 4 errors; aborting
```

I'm running:
Firebase.core version 3.0.2
Firebase.analytics version 2.2.2
Titanium SDK version 7.5.0.GA

I'm a little clueless as to what went wrong, so I welcome any suggestion.

Many thanks in advance,
Stefan Bakker

**Comment by cristophergv** [comment]
Hello,

I have the same problem :(

I test with Titanium SDK from 7.2 to 7.5 :(

Thank you.

**Comment by hansemannn** [comment]
Hardcode your ti.playservices to 11.0.40

**Comment by cristophergv** [comment]
Yes is correct. Thank you Hansemannn.
