### ISSUE TITLE
Firebase Module not receiving our uncaughtException 

### ISSUE THREAD

**Issue by bubinf** [hansemannn/titanium-firebase-analytics#45]
we have set up
Ti.App.addEventListener('uncaughtException',function(evt) {
var dictionary = {
					 name: 'testing',
					 reason: evt.message,
					 frames: evt.stackTrace.split("+")
				 };

				 Crashlytics.recordCustomException(dictionary);
}

Firebase is not receiving this message

**Comment by hansemannn** [comment]
This is the wrong repo
