### ISSUE TITLE
iOS ** BUILD FAILED **, Android crash

### ISSUE THREAD

**Issue by argum** [hansemannn/titanium-firebase-analytics#5]
Hello, 

I have added firebase.core && firebase.analytics module in my Appcelerator App (SDK 6.3.0.GA) 

The build fails on iOS (real iPhone 6S and iPhone 5S simulator) with the same error message:

[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/appName.app/appName normal x86_64
[ERROR] :  (1 failure)

No other modules are been added to this project.

On android, app compiles but it shows an error:

Uncaught com.google.android.gms.commo.internal.zzby
FirebaseCore.configure().

Do I need any extra module in order to work?

Thanks!

**Comment by hansemannn** [comment]
You need to include the `titanium-firebase-core` module as well, also the `ti.playservices` module for Android.

**Comment by argum** [comment]
Hello hansemannn, thanks for your quick reply. Howevery, both are included:

<module platform="iphone">firebase.core</module>
        <module platform="android">firebase.core</module>
        <module platform="iphone">firebase.analytics</module>
        <module platform="android">firebase.analytics</module>

Could you please give me any idea?
