### ISSUE TITLE
Bug on param "value" of event "ecommerce_purchase" in android

### ISSUE THREAD

**Issue by LudoFont** [hansemannn/titanium-firebase-analytics#50]
Hi,
I log the event "ecommerce_purchase" in my iOS/android app, and for every event logged in android, i have the following firebase_error for the parameter named "value" : 
`18 : Invalid value parameter type`

In this event, the param "value" must be a double, and i have no problems when my code is executed in my iOS app, i make sure to use a parseFloat() in my code : 

```
FirebaseAnalytics.log('ecommerce_purchase', {
        transaction_id: transaction_id,
        location: location,
        value: parseFloat(cmd.total),
        currency: 'EUR'
});
```

Can you do something about this issue please ?

**Comment by hansemannn** [comment]
Some events are blacklisted by Google, please use an app prefix in that case, e.g. `my_app_ecommerce_purchase` or use the built in events
