### ISSUE TITLE
Several "not set" values in Firebase Analytics Events

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-firebase-analytics#53]
I've got a lot of `not set` values in my events. I'm firing the events all the same and be sure, that the labels and the UserPropertyString is NOT empty. Anyways, there are these `not set` values.

<img width="498" alt="Bildschirmfoto 2019-10-02 um 09 15 31" src="https://user-images.githubusercontent.com/1126641/66025167-152eff00-e4f6-11e9-8ce2-f3d2634b5f40.png">

<img width="511" alt="Bildschirmfoto 2019-10-02 um 09 15 24" src="https://user-images.githubusercontent.com/1126641/66025177-195b1c80-e4f6-11e9-8932-f8f1bf6ebc49.png">

How can I avoid this? From where does this behavior is sourced?

**Comment by dublin-anondson-movista** [comment]
@caspahouzer did you ever figure out what was going on to cause that? I've been having the same problem and have yet to figure out what's going on. I thought it might be related to [this stackoverflow](https://stackoverflow.com/questions/52871794/not-set-is-showing-on-firebase-analytics-dashboard) question but I've had no luck by converting the values I'm passing.

**Comment by dublin-anondson-movista** [comment]
Figured my problem out, when passing parameters I was setting the key and value to the same value
`{aVeryUniqueValue: aVeryUniqueValue}`. And not defining them correctly within firebase so they weren't ever showing up. 

Changing it to a concrete param name like `{userAction: aVeryUniqueValue}` fixed it.
