### ISSUE TITLE
Error when using module in Android

### ISSUE THREAD

**Issue by stefanovic72** [hansemannn/titanium-firebase-analytics#6]
Hi,
I'm getting this (runtime) error when I try to use the module in Android:
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/zza;
[ERROR] :  1 error; aborting

Any idea what the cause of this error can be?

**Comment by hansemannn** [comment]
Please check out the [Android notes](https://github.com/hansemannn/titanium-firebase-analytics#android-note), it states the SDK compatibility and other dependencies.
