### ISSUE TITLE
Firebase core and analytics module is not working in android build

### ISSUE THREAD

**Issue by rasingh2224** [hansemannn/titanium-firebase-analytics#64]
Hi,

I have installed both firebase core and firebase analytics module in my app. IOS app is working fine but android build is giving following error. 

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Event;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Param;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$UserProperty;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$ConditionalUserProperty;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$Event;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$EventInterceptor;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/measurement/AppMeasurement$OnEventListener;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:365)
[ERROR] :  	at com.android.dx.command.dexer.Main.runDx(Main.java:286)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:244)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:95)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
[ERROR] :  	... 4 more
[ERROR] Application Installer abnormal process termination. Process exit value was 1

App is using following versions
Titanium sdk: 8.3.1.GA
Firebase core: 3.0.0
Firebase analytics: 2.1.2
ti.playservices : 16.1.3
ti,cloudpush: 5.1.2
ti.admob: 4.3.0
ti.map: 3.1.1

**Comment by hansemannn** [comment]
please make sure to use the correct version combination
