### ISSUE TITLE
iOS Analytics alert in Firebase

### ISSUE THREAD

**Issue by macasfaj** [hansemannn/titanium-firebase-analytics#83]
Hi! I've checked my Firebase Console and I see this new alert. Max date is tomorrow:

<img width="1053" alt="image" src="https://github.com/hansemannn/titanium-firebase-analytics/assets/2458748/9740ff94-f4a0-44b2-a1bb-94cf59e36680">

I'm updating Core + Analytics + Crashlytics to the most recent releases. But I think that we're not covering 10.24.0. 

 Is there any fix for that or do we need new iOS release? Thanks!

**Comment by m1ga** [comment]
please try this version: [firebase.analytics-iphone-9.1.0.zip](https://github.com/hansemannn/titanium-firebase-analytics/files/15264547/firebase.analytics-iphone-9.1.0.zip)


I've downloaded the latest framework (10.25.0) and rebuild the module. Didn't test it though :)

**Comment by macasfaj** [comment]
Hi @m1ga 

Using 9.0.0 I can run on Simulator + build perfectly.

But if I replace with new build 9.1.0, we get this running on simulator or building for Apple App Store.

I we return to 9.0.0, all is good again.

Any help, please?

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=development')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than '__LOG__ID__=61a3c120-a7e9-4117-8fd9-962e1a880fb7')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEBUG=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DISABLE_TI_LOG_SERVER=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.2.0')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=development')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than '__LOG__ID__=61a3c120-a7e9-4117-8fd9-962e1a880fb7')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEBUG=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DISABLE_TI_LOG_SERVER=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.2.0')
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/migue/Documents/Titanium/mobile-client/build/iphone/build/Intermediates/Myapp/Debug-iphonesimulator/Supernova.build/Objects-normal/arm64/Binary/Myapp normal arm64 (in target 'Myapp' from project 'Myapp')

**Comment by m1ga** [comment]
which Xcode version are you using? Not the first time this week that I see that error

**Comment by macasfaj** [comment]
Xcode 15.3

**Comment by Astrovic** [comment]
@macasfaj  I updated it to 10.25.0 https://github.com/hansemannn/titanium-firebase-analytics/pull/84

**Comment by macasfaj** [comment]
Thanks!!! let me check!

**Comment by macasfaj** [comment]
I still get this:

[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=development')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEPLOYTYPE=development')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than '__LOG__ID__=61a3c120-a7e9-4117-8fd9-962e1a880fb7')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than '__LOG__ID__=61a3c120-a7e9-4117-8fd9-962e1a880fb7')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEBUG=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DEBUG=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DISABLE_TI_LOG_SERVER=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'DISABLE_TI_LOG_SERVER=1')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.2.0')
[ERROR] warning: conditional compilation flags do not have values in Swift; they are either present or absent (rather than 'TI_VERSION=12.2.0')
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/migue/Documents/Titanium/mobile-client/build/iphone/build/Intermediates/.....

:(

**Comment by macasfaj** [comment]
@Astrovic My fault, I needed to update Core too and it's working like a charm. Thanks!!
