### ISSUE TITLE
Getting an not found for architecture x86_64 error on 6.2.2 and ios11.2

### ISSUE THREAD

**Issue by amigoni** [hansemannn/titanium-firebase-analytics#9]
[TRACE] :  ld: symbol(s) not found for architecture x86_64
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[TRACE] :  Showing first 200 notices only

**Comment by hansemannn** [comment]
Please attach a full trace-log and try the latest version. As no other users experienced this issue so far, it may be something with your outdated SDK as well. Let me know and I'll reopen the issue if necessary, thx!

**Comment by mitulbhalia** [comment]
Hello @hansemannn 

I am getting below error while integrating iphone module.
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/test.app/test normal x86_64
[ERROR] :  (1 failure)

I used 6.2.2 and 6.3.1 ti sdk with 1.0.0 and 1.1.0 module version. App works well if i remove the module.
Xcode : 8.3.3
iOS : 10.3
CLI : 7.0
Please provide solution asap.

**Comment by hansemannn** [comment]
Just tested using Xcode 9 and SDK 7.0.1 and it works fine. No official support for outdated platforms and versions.

**Comment by mitulbhalia** [comment]
Ok, will you please confirm the steps I followed to integrate module?

1-> Added firebase.analytics and firebase.core module in tiapp.xml
2-> put GoogleConfig-Info.plist in app/assets/iphone folder
3-> require analytics module in alloy.js

Is there anything I am missing?

**Comment by hansemannn** [comment]
I've published my sample app, please ensure to have the required config files as well, those are not included in the repo. https://github.com/hansemannn/titanium-firebase-demo

This is the last support comment. For more help, please either ask the [Slack community](http://tislack.org) or purchase [advanced support](http://shop.hans-knoechel.de/product/premium-support/).

**Comment by mitulbhalia** [comment]
Hi @amigoni 
Did you find any solution?

**Comment by LilianAlvarez** [comment]
@mitulbhalia : for me everything is working except User properties that i can not get..
